# Generated by Django 4.0.10 on 2024-04-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_join',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_superAdmin',
            new_name='is_superuser',
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
