# Generated by Django 5.0.6 on 2024-05-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_is_superadmin_account_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_superuser',
            new_name='is_superadmin',
        ),
    ]
