# Generated by Django 4.0.10 on 2024-05-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='vartiation_value',
            new_name='variation_value',
        ),
    ]
