# Generated by Django 5.0.4 on 2024-05-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_create_date_variation_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='title', max_length=300, unique=True),
        ),
    ]
