# Generated by Django 5.0.4 on 2024-05-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
