# Generated by Django 5.0.4 on 2024-05-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
