# Generated by Django 5.0.4 on 2024-05-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_purchasehistory_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='ordered',
        ),
    ]
