# Generated by Django 5.0.4 on 2024-05-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_product'),
        ('store', '0008_product_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='pr',
        ),
    ]
