# Generated by Django 5.0.4 on 2024-05-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_product_pr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pr',
        ),
    ]
