# Generated by Django 5.0.6 on 2024-05-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_is_superuser_account_is_superadmin'),
        ('orders', '0007_delete_pr'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(default=-1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='accounts.userprofile')),
            ],
        ),
    ]
